restore_registry: &RESTORE_REGISTRY
  restore_cache:
    key: registry
save_registry: &SAVE_REGISTRY
  save_cache:
    key: registry-{{ .BuildNum }}
    paths:
    - /usr/local/cargo/registry/index
deps_key: &DEPS_KEY
  key: deps-{{ checksum "~/rust-version" }}-{{ checksum "Cargo.lock" }}
restore_deps: &RESTORE_DEPS
  restore_cache:
    <<: *DEPS_KEY
save_deps: &SAVE_DEPS
  save_cache:
    <<: *DEPS_KEY
    paths:
    - target
    - /usr/local/cargo/registry/cache

version: 2.1
jobs:
  build-clippy-test-macros:
    docker:
      - image: rust:1.34.1-stretch
    steps:
      - checkout
      - run: rustup component add clippy --toolchain 1.34.1-x86_64-unknown-linux-gnu
      - run: RUSTFLAGS="-D warnings" cargo build -p keg --all-features
      - run: cargo test -p keg-macros
      - run: RUSTFLAGS="-D warnings" cargo clippy -p keg -p keg-functions -p keg-macros
  test-sqlite:
    docker:
      - image: rust:1.34.1-stretch
    steps:
      - checkout
      - run: cargo build -p keg --features "rusqlite"
      - run: cd keg && cargo test -p keg --features "trusqlite" --test rusqlite
  test-postgres:
    docker:
      - image: rust:1.34.1-stretch
      - image: postgres:9.6.13-alpine
    steps:
      - checkout
      - run: cargo build -p keg --features "postgres"
      - run: cd keg && cargo test -p keg --features "tpostgres" --test postgres -- --test-threads 1
  test-mysql:
    docker:
      - image: rust:1.34.1-stretch
      - image: mariadb:5.5.64-trusty
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: keg
          MYSQL_PASSWORD: root
          MYSQL_DATABASE: keg_test
    steps:
      - checkout
      - run: cargo build -p keg --features "mysql"
      - run: cd keg && cargo test -p keg --features "tmysql" --test mysql -- --test-threads 1
workflows:
  version: 2
  build_and_test:
    jobs:
      - build-clippy-test-macros
      - test-sqlite
      - test-postgres
      - test-mysql
