[package]
name = "keg-functions"
version = "0.1.0"
authors = ["João Oliveira <hello@jxs.pt>"]
edition = "2018"

[features]
default = []

[dependencies]
lazy_static = "1.3.0"
regex = "1.1.6"
rusqlite = {version = "0.18.0", optional = true}
log = "0.4.6"
